# Generated by Django 3.1.7 on 2021-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceDataAverage',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('dimen_id', models.CharField(db_column='DIMEN_ID', max_length=255)),
                ('time', models.CharField(blank=True, db_column='TIME', max_length=255, null=True)),
                ('indus_id', models.CharField(db_column='INDUS_ID', max_length=255)),
                ('province', models.CharField(blank=True, db_column='PROVINCE', max_length=255, null=True)),
                ('scale', models.CharField(blank=True, db_column='SCALE', max_length=255, null=True)),
                ('bs_id', models.CharField(db_column='BS_ID', max_length=255)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=255, null=True)),
                ('value', models.CharField(blank=True, db_column='VALUE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'balance_data_average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceIndex',
            fields=[
                ('bs_id', models.CharField(db_column='BS_ID', max_length=255, primary_key=True, serialize=False)),
                ('bs_name', models.CharField(blank=True, db_column='BS_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'balance_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashDataAverage',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('dimen_id', models.CharField(db_column='DIMEN_ID', max_length=255)),
                ('time', models.CharField(blank=True, db_column='TIME', max_length=255, null=True)),
                ('indus_id', models.CharField(db_column='INDUS_ID', max_length=255)),
                ('province', models.CharField(blank=True, db_column='PROVINCE', max_length=255, null=True)),
                ('scale', models.CharField(blank=True, db_column='SCALE', max_length=255, null=True)),
                ('cf_id', models.CharField(db_column='CF_ID', max_length=255)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=255, null=True)),
                ('value', models.CharField(blank=True, db_column='VALUE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cash_data_average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashIndex',
            fields=[
                ('cf_id', models.CharField(db_column='CF_ID', max_length=255, primary_key=True, serialize=False)),
                ('cf_name', models.CharField(blank=True, db_column='CF_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cash_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('dimen_id', models.CharField(db_column='DIMEN_ID', max_length=255, primary_key=True, serialize=False)),
                ('dimen_name', models.CharField(blank=True, db_column='DIMEN_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'datetime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexappUserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'indexapp_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexappUsertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'indexapp_usertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('indus_id', models.CharField(db_column='INDUS_ID', max_length=255, primary_key=True, serialize=False)),
                ('indus_name', models.CharField(blank=True, db_column='INDUS_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'industry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitDataAverage',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('dimen_id', models.CharField(db_column='DIMEN_ID', max_length=255)),
                ('time', models.CharField(blank=True, db_column='TIME', max_length=255, null=True)),
                ('indus_id', models.CharField(db_column='INDUS_ID', max_length=255)),
                ('province', models.CharField(blank=True, db_column='PROVINCE', max_length=255, null=True)),
                ('scale', models.CharField(blank=True, db_column='SCALE', max_length=255, null=True)),
                ('ps_id', models.CharField(db_column='PS_ID', max_length=255)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=255, null=True)),
                ('value', models.CharField(blank=True, db_column='VALUE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'profit_data_average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitIndex',
            fields=[
                ('ps_id', models.CharField(db_column='PS_ID', max_length=255, primary_key=True, serialize=False)),
                ('ps_name', models.CharField(blank=True, db_column='PS_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'profit_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('dis_id', models.CharField(db_column='DIS_ID', max_length=255, primary_key=True, serialize=False)),
                ('dis_name', models.CharField(blank=True, db_column='DIS_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('scale_id', models.CharField(db_column='SCALE_ID', max_length=255, primary_key=True, serialize=False)),
                ('scale_name', models.CharField(blank=True, db_column='SCALE_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'scale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadingOfBalance',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=255, primary_key=True, serialize=False)),
                ('user_time', models.CharField(blank=True, db_column='USER_TIME', max_length=255, null=True)),
                ('bs_id', models.CharField(db_column='BS_ID', max_length=255)),
                ('bs_name', models.CharField(blank=True, db_column='BS_NAME', max_length=255, null=True)),
                ('values', models.CharField(blank=True, db_column='VALUES', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uploading_of_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadingOfCash',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=255, primary_key=True, serialize=False)),
                ('user_time', models.CharField(blank=True, db_column='USER_TIME', max_length=255, null=True)),
                ('cf_id', models.CharField(db_column='CF_ID', max_length=255)),
                ('cf_name', models.CharField(blank=True, db_column='CF_NAME', max_length=255, null=True)),
                ('values', models.CharField(blank=True, db_column='VALUES', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uploading_of_cash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadingOfProfit',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=255, primary_key=True, serialize=False)),
                ('user_time', models.CharField(blank=True, db_column='USER_TIME', max_length=255, null=True)),
                ('ps_id', models.CharField(db_column='PS_ID', max_length=255)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=255, null=True)),
                ('ps_name', models.CharField(blank=True, db_column='PS_NAME', max_length=255, null=True)),
                ('values', models.CharField(blank=True, db_column='VALUES', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uploading_of_profit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_id', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=255)),
                ('key', models.CharField(db_column='KEY', max_length=255)),
            ],
            options={
                'db_table': 'user_information',
                'managed': False,
            },
        ),
    ]
